
package soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloService", targetNamespace = "http://soap/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloService {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://soap/", className = "soap.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://soap/", className = "soap.SayHelloResponse")
    @Action(input = "http://soap/HelloService/sayHelloRequest", output = "http://soap/HelloService/sayHelloResponse")
    public String sayHello();

    /**
     * 
     * @return
     *     returns soap.Personne
     */
    @WebMethod
    @WebResult(name = "personne", targetNamespace = "")
    @RequestWrapper(localName = "getPersonne", targetNamespace = "http://soap/", className = "soap.GetPersonne")
    @ResponseWrapper(localName = "getPersonneResponse", targetNamespace = "http://soap/", className = "soap.GetPersonneResponse")
    @Action(input = "http://soap/HelloService/getPersonneRequest", output = "http://soap/HelloService/getPersonneResponse")
    public Personne getPersonne();

    /**
     * 
     * @param prenom
     * @param nom
     * @return
     *     returns soap.Personne
     */
    @WebMethod
    @WebResult(name = "personne", targetNamespace = "")
    @RequestWrapper(localName = "getPersonneInit", targetNamespace = "http://soap/", className = "soap.GetPersonneInit")
    @ResponseWrapper(localName = "getPersonneInitResponse", targetNamespace = "http://soap/", className = "soap.GetPersonneInitResponse")
    @Action(input = "http://soap/HelloService/getPersonneInitRequest", output = "http://soap/HelloService/getPersonneInitResponse")
    public Personne getPersonneInit(
        @WebParam(name = "prenom", targetNamespace = "")
        String prenom,
        @WebParam(name = "nom", targetNamespace = "")
        String nom);

}
