
package services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "villeservice", targetNamespace = "http://services/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Villeservice {


    /**
     * 
     * @param nom
     * @return
     *     returns services.Ville
     */
    @WebMethod
    @WebResult(name = "ville", targetNamespace = "")
    @RequestWrapper(localName = "getInfo", targetNamespace = "http://services/", className = "services.GetInfo")
    @ResponseWrapper(localName = "getInfoResponse", targetNamespace = "http://services/", className = "services.GetInfoResponse")
    @Action(input = "http://services/villeservice/getInfoRequest", output = "http://services/villeservice/getInfoResponse")
    public Ville getInfo(
        @WebParam(name = "nom", targetNamespace = "")
        String nom);

}
